plugins {
    id 'com.android.application'
}

android {
    namespace 'com.retrolootpro.clover'
    compileSdk 35

    defaultConfig {
        applicationId 'com.retrolootpro.clover'
        minSdk 23
        targetSdk 25
        versionCode 1
        versionName '0.1.0'
    }

    signingConfigs.configureEach {
        enableV1Signing = true
        enableV2Signing = false
        enableV3Signing = false
        enableV4Signing = false
    }

    lint {
        disable 'ExpiredTargetSdkVersion'
    }
}

dependencies {
    implementation 'com.clover.sdk:clover-android-sdk:262.2'
    implementation 'com.clover.sdk:clover-android-connector-sdk:262.2'
}
