android.useAndroidX=true
android.nonTransitiveRClass=true
android.injected.signing.v1-enabled=true
android.injected.signing.v2-enabled=false
android.injected.signing.v3-enabled=false
android.injected.signing.v4-enabled=false
android.defaults.buildfeatures.resvalues=true
android.sdk.defaultTargetSdkToCompileSdkIfUnset=false
android.enableAppCompileTimeRClass=false
android.usesSdkInManifest.disallowed=false
android.uniquePackageNames=false
android.dependency.useConstraints=true
android.r8.strictFullModeForKeepRules=false
android.r8.optimizedResourceShrinking=false
android.builtInKotlin=false
android.newDsl=false
