import {
  AlertTriangle,
  Archive,
  Barcode,
  BookOpen,
  Boxes,
  Calculator,
  ClipboardCheck,
  DollarSign,
  FileText,
  Gavel,
  HelpCircle,
  LayoutDashboard,
  ListChecks,
  Package,
  ReceiptText,
  Search,
  Settings,
  FileLock2,
  KeyRound,
  ShieldAlert,
  ShoppingBasket,
  Truck,
  WalletCards,
} from 'lucide-react';
import type { ElementType } from 'react';

export type ManualSection = {
  id: string;
  title: string;
  category: string;
  icon: ElementType;
  summary: string;
  why: string;
  steps: string[];
  fields?: string[];
  warnings?: string[];
};

export type ManualGuide = {
  id: string;
  title: string;
  summary: string;
  steps: string[];
};

export const manualSections: ManualSection[] = [
  {
    id: 'getting-started',
    title: 'Getting Started',
    category: 'Start Here',
    icon: BookOpen,
    summary: 'Use RetroLootPro as the daily command center for inventory, pricing, tasks, sales, shipping, finance, and disputes.',
    why: 'A consistent workflow keeps items from getting lost, double listed, underpriced, or forgotten in storage.',
    steps: [
      'Start on the Dashboard each day.',
      'Review alerts, tasks due, aging inventory, and high-priority items.',
      'Add new purchases through a shipment, lot, scan, or manual inventory entry.',
      'Refresh pricing before listing or discounting items.',
      'Use tasks to move items through cleaning, testing, photos, pricing, listing, and shipping.',
    ],
  },
  {
    id: 'dashboard-overview',
    title: 'Dashboard Overview',
    category: 'Daily Operations',
    icon: LayoutDashboard,
    summary: 'The Dashboard should answer what needs attention today without showing every detail in the business.',
    why: 'A focused dashboard helps you make daily decisions quickly: list, price, clean, sell, ship, or wait.',
    steps: [
      'Check portfolio value and inventory count.',
      'Review aging inventory alerts.',
      'Open hot deals to verify pricing or listing status.',
      'Use quick actions for scanning, manual entry, show prep, or inventory review.',
    ],
    warnings: [
      'Aging alerts mean an item may need a price change, new photos, a different sales channel, or bundling.',
      'Market value is only as good as the most recent pricing refresh.',
    ],
  },
  {
    id: 'inventory-management',
    title: 'Inventory Management',
    category: 'Inventory',
    icon: Package,
    summary: 'Inventory is the source of truth for every item you own, where it is, what it cost, what it is worth, and what should happen next.',
    why: 'Clean inventory records protect profit and prevent double selling, missed listings, or bad buying decisions.',
    steps: [
      'Use search to find an item by title or platform.',
      'Filter by status, platform, condition, region, age, and collection.',
      'Sort by name, age, cost, market value, or profit.',
      'Open an item to review pricing, condition, listing content, tasks, and notes.',
    ],
    fields: [
      'Status tracks where the item is in the workflow.',
      'Condition controls the market value used for profit calculations.',
      'Region helps separate US, JP, PAL, and other versions.',
      'Storage location or collection helps you physically find the item.',
    ],
  },
  {
    id: 'adding-items',
    title: 'Adding Items',
    category: 'Inventory',
    icon: Barcode,
    summary: 'Items can be added by scan, manual UPC entry, manual title entry, or lot workflow when available.',
    why: 'Adding items consistently makes cost basis, pricing, and task automation work correctly.',
    steps: [
      'Create or select the shipment or lot when the purchase belongs to one.',
      'Scan the UPC or search by title.',
      'Confirm title, platform, condition, region, and quantity.',
      'Add notes for missing manuals, damage, import region, or testing needs.',
      'Refresh metadata and pricing before listing.',
    ],
    warnings: [
      'If a scan finds an existing item, confirm whether this is a second copy or an accidental duplicate scan.',
      'Do not guess condition if the item still needs cleaning or testing. Use Untested or Damaged when appropriate.',
    ],
  },
  {
    id: 'bulk-import',
    title: 'Bulk Import',
    category: 'Inventory',
    icon: FileText,
    summary: 'Bulk import is for adding many records from a file or marketplace report when supported.',
    why: 'Bulk import saves time, but imported data should be reviewed for duplicates and missing fields.',
    steps: [
      'Open the import tool from the matching area, such as Finance transactions for statements.',
      'Upload the CSV file.',
      'Review detected source, dates, names, amounts, and transaction types.',
      'Skip or accept duplicate-looking rows.',
      'Check totals after import.',
    ],
  },
  {
    id: 'pricing-engine',
    title: 'Pricing Engine',
    category: 'Pricing',
    icon: Calculator,
    summary: 'Pricing compares available sources and stores current market values for each condition.',
    why: 'Accurate pricing protects margin and helps decide whether to list, bundle, discount, or hold.',
    steps: [
      'Open an item and refresh pricing if the last check is old.',
      'Review Loose, CIB, New, and Graded values when available.',
      'Check the recommended ask, quick-sale price, floor, and emergency floor.',
      'Use manual overrides only when you know the automated price is wrong.',
    ],
    fields: [
      'Recommended ask is the normal listing target.',
      'Quick-sale price is used when you want faster cash recovery.',
      'Floor price is the lowest normal price before the deal stops making sense.',
      'Emergency floor is for clearance or cash crunch situations.',
      'Confidence score shows how reliable the pricing match appears.',
    ],
    warnings: [
      'If price is below floor, profit may be too low after fees and shipping.',
      'If the item has been sitting too long, a lower price or different channel may be smarter.',
    ],
  },
  {
    id: 'sell-channel-recommendations',
    title: 'Sell-Channel Recommendations',
    category: 'Pricing',
    icon: ShoppingBasket,
    summary: 'Sell-channel recommendations help decide whether an item belongs on eBay, Whatnot, local sale, Amazon, in a bundle, or should be held.',
    why: 'The best sales channel depends on value, demand, condition, shipping cost, margin, and how quickly cash is needed.',
    steps: [
      'Open the item detail page.',
      'Review the Sell Plan section.',
      'Compare the recommended channel with your current workflow.',
      'Move slow or low-value items into bundles or shows when appropriate.',
    ],
  },
  {
    id: 'lot-analyzer',
    title: 'Lot Analyzer',
    category: 'Sourcing',
    icon: Search,
    summary: 'The Lot Analyzer helps review a possible purchase before spending money.',
    why: 'It protects cash by estimating resale value, max buy price, worst-case value, and risk before you buy.',
    steps: [
      'Open Sourcing / Lot Analyzer.',
      'Enter the lot name, source, supplier, asking price, shipping, and fees.',
      'Add estimated items and values.',
      'Review max buy price, expected profit, worst case, and risk flags.',
      'Save the analysis with a buy, risky, pass, or needs review decision.',
    ],
    warnings: [
      'A good resale value does not always mean a good buy if cash flow, fees, shipping, or slow movers are a problem.',
    ],
  },
  {
    id: 'whatnot-show-builder',
    title: 'Whatnot Show Builder',
    category: 'Sales Channels',
    icon: ListChecks,
    summary: 'Whatnot Shows organize inventory into a live selling plan with run order, price targets, and notes.',
    why: 'A prepared show reduces mistakes during a fast live sale and makes post-show profit easier to review.',
    steps: [
      'Create a show.',
      'Add inventory items that are ready to sell.',
      'Set run order, starting bid, floor, BIN price, and notes.',
      'Mark items sold after the show.',
      'Review post-show profit and update inventory status.',
    ],
  },
  {
    id: 'ebay-listing-support',
    title: 'eBay Listing Support',
    category: 'Sales Channels',
    icon: Gavel,
    summary: 'eBay listing support uses item data to prepare titles, descriptions, prices, and status tracking.',
    why: 'Drafting from inventory reduces typing and keeps sold/listed status tied back to the item.',
    steps: [
      'Open a ready-to-list item.',
      'Review pricing and condition notes.',
      'Generate or edit listing content.',
      'Create a draft or mark the item as listed.',
      'Store the listing URL and update status when sold.',
    ],
  },
  {
    id: 'bundle-builder',
    title: 'Bundle Builder',
    category: 'Sales Channels',
    icon: Boxes,
    summary: 'Bundles group items together by platform, franchise, category, slow-mover status, import region, or clearance plan.',
    why: 'Bundling can turn low-value or slow-moving items into useful cash without listing each item separately.',
    steps: [
      'Open Planning, then Bundles.',
      'Name the bundle and choose a strategy.',
      'Select inventory items.',
      'Review cost basis, market value, ask price, floor, and expected profit.',
      'List the bundle or assign it to a show.',
    ],
  },
  {
    id: 'tasks-prep-workflow',
    title: 'Tasks / Prep Workflow',
    category: 'Operations',
    icon: ClipboardCheck,
    summary: 'Tasks move work through scanning, cleaning, testing, photos, pricing, listing, packing, shipping, and approval.',
    why: 'A task queue helps employees or helpers know exactly what to do without guessing.',
    steps: [
      'Generate tasks from inventory when items are missing prep steps.',
      'Assign work to a person.',
      'Complete checklist items.',
      'Mark the task complete.',
      'Admins approve completed work when needed.',
    ],
    fields: [
      'Task status shows whether work is open, assigned, in progress, completed, approved, blocked, or cancelled.',
      'Piece rate and time estimate help track labor cost.',
    ],
  },
  {
    id: 'condition-checklists',
    title: 'Testing and Condition Checklists',
    category: 'Operations',
    icon: ClipboardCheck,
    summary: 'Condition checklists record what was cleaned, tested, included, missing, damaged, or unverified.',
    why: 'Good condition records reduce refunds and make listing descriptions safer.',
    steps: [
      'Open the item.',
      'Record cleaned, tested, manual, case, artwork, region, and notes for games.',
      'For consoles, record power, disc or cart reading, buttons, ports, cords, reset status, serial number, and issues.',
      'Keep photo proof when available.',
    ],
  },
  {
    id: 'shipping-workflow',
    title: 'Shipping and Packing Workflow',
    category: 'Operations',
    icon: Truck,
    summary: 'Shipping tracks package weight, dimensions, method, tracking, insurance, packing materials, and packing photos.',
    why: 'Shipping records protect you during disputes and help calculate true profit.',
    steps: [
      'Open Shipping or the sold item.',
      'Enter package weight and dimensions.',
      'Choose box or mailer type and shipping method.',
      'Add tracking and insurance if used.',
      'Save packing photos for higher-risk orders.',
    ],
  },
  {
    id: 'secure-document-vault',
    title: 'Secure Document Vault',
    category: 'Admin',
    icon: FileLock2,
    summary: 'The document vault stores important business records such as EIN letters, LLC documents, sales certificates, reseller permits, insurance, tax records, and contracts.',
    why: 'Employees and admins need important documents quickly, but those documents should not sit in email threads or random folders.',
    steps: [
      'Open Documents.',
      'Enter the shared vault passphrase.',
      'Upload the document with a clear title and document type.',
      'Choose Team visibility for employee-needed documents or Admin Only for sensitive records.',
      'Use Decrypt to download a readable copy when needed.',
      'Store the vault passphrase in a password manager. The app cannot recover it if lost.',
    ],
    warnings: [
      'Files are encrypted in the browser before upload.',
      'The passphrase is not stored by RetroLootPro.',
      'Anyone with the passphrase and app access can decrypt team-visible documents.',
    ],
  },
  {
    id: 'security-mfa',
    title: 'Security and MFA',
    category: 'Admin',
    icon: KeyRound,
    summary: 'Security settings let admins require MFA and let users enroll authenticator app or SMS verification factors.',
    why: 'MFA reduces the chance that a stolen password can expose business data, inventory, finance records, or sensitive documents.',
    steps: [
      'Open Settings.',
      'Use Security Controls to enroll an authenticator app or SMS factor.',
      'Admins can enable Require MFA for the account.',
      'When MFA is required, users must verify a factor before using protected areas.',
      'Passkeys are listed as planned until a supported WebAuthn provider is wired in.',
    ],
    warnings: [
      'SMS requires phone MFA/SMS provider configuration in Supabase.',
      'Keep recovery options and admin access documented before requiring MFA for everyone.',
    ],
  },
  {
    id: 'finance-overview',
    title: 'Finance Overview',
    category: 'Finance',
    icon: DollarSign,
    summary: 'Finance tracks money in, money out, expenses, imported statements, lots, loans, taxes, banks, and profit.',
    why: 'The business needs to know true profit, cash available, debt, tax reserve, and whether buying more inventory is safe.',
    steps: [
      'Start with Overview for the big picture.',
      'Use Transactions for imported or manual money activity.',
      'Use Expenses to track potential write-offs by person, receipt, category, and business purpose.',
      'Use Lots to monitor break-even.',
      'Use Loans for money borrowed from yourself or other sources.',
      'Use Taxes and P&L for review.',
    ],
  },
  {
    id: 'expense-tracking',
    title: 'Expense Tracking and Write-Off Prep',
    category: 'Finance',
    icon: ReceiptText,
    summary: 'Expenses records business costs that may become tax write-offs, including who paid, amount, merchant, category, receipt link, and business purpose.',
    why: 'Small costs like shipping supplies, platform fees, mileage, software, and show fees add up. Tracking them as they happen keeps tax prep simple and shows expense totals by person.',
    steps: [
      'Open Finance, then Expenses.',
      'Click Add Expense.',
      'Choose the person who paid or incurred the expense.',
      'Select the write-off category that best matches the cost.',
      'Add the date, amount, merchant, receipt link, and business purpose.',
      'Use Draft for uncertain items, Ready for tax review, Reviewed after checking, and Do Not Claim for disallowed costs.',
      'Open Insights to review total expense value by person.',
    ],
    fields: [
      'Person means the invited user or team member connected to the expense.',
      'Write-off category is a tax-prep bucket based on common IRS Schedule C categories.',
      'Business purpose explains why the cost was ordinary and necessary for the business.',
      'Receipt URL can be a link to a receipt, file, image, or storage location.',
    ],
    warnings: [
      'This tracker is for records and planning, not tax advice.',
      'Inventory costs are usually handled through cost of goods sold, not always as an immediate operating expense.',
      'Ask a CPA before claiming uncertain expenses, home office, vehicle, meals, depreciation, or mixed personal/business costs.',
    ],
  },
  {
    id: 'safe-buying-budget',
    title: 'Safe Buying Budget',
    category: 'Finance',
    icon: WalletCards,
    summary: 'Safe buying budget is the amount you can spend on more inventory without hurting bills, taxes, debt, or cash flow.',
    why: 'Buying too much inventory can create profit on paper but leave the business short on cash.',
    steps: [
      'Review cash available.',
      'Subtract upcoming expenses, tax reserve, debt payments, and required operating cushion.',
      'Review inventory already tied up.',
      'Use the remaining safe amount as your buying limit.',
    ],
  },
  {
    id: 'lot-cost-allocation',
    title: 'Lot Cost Allocation',
    category: 'Finance',
    icon: Calculator,
    summary: 'Lot cost allocation spreads the total price paid across items based on each item market value.',
    why: 'This gives each item a realistic cost of goods instead of guessing an equal cost for every game.',
    steps: [
      'Confirm the lot was received.',
      'Enter total amount paid, shipping, taxes, and fees.',
      'Scan or add every item in the lot.',
      'Refresh market value for each item.',
      'Allocate cost based on each item share of total market value.',
    ],
  },
  {
    id: 'break-even-tracking',
    title: 'Break-Even Tracking',
    category: 'Finance',
    icon: Calculator,
    summary: 'Break-even shows whether a lot has recovered its total cost after sales.',
    why: 'A lot can contain profitable items but still not be paid back yet.',
    steps: [
      'Open Finance, then Lots.',
      'Review total paid, sales collected, and remaining break-even amount.',
      'Prioritize selling items from lots that have not broken even.',
    ],
  },
  {
    id: 'debt-credit-tracking',
    title: 'Debt and Credit Tracking',
    category: 'Finance',
    icon: WalletCards,
    summary: 'Debt tracking records money borrowed by the business, including money borrowed from yourself.',
    why: 'Repayments should be tracked separately from profit so the business does not look healthier than it is.',
    steps: [
      'Open Finance, then Loans.',
      'Create the loan with lender, amount, date, and notes.',
      'Link repayments to transactions when possible.',
      'Review remaining balance before buying more inventory.',
    ],
  },
  {
    id: 'tax-reserve-tool',
    title: 'Tax Reserve Tool',
    category: 'Finance',
    icon: FileText,
    summary: 'Tax reserve estimates money to set aside for taxes based on sales and profit activity.',
    why: 'Keeping tax money visible helps avoid spending cash that does not really belong to inventory buying.',
    steps: [
      'Open Finance, then Taxes.',
      'Review taxable activity and estimated reserve.',
      'Update the reserve after large sales, refunds, or expense imports.',
    ],
  },
  {
    id: 'dispute-evidence-vault',
    title: 'Dispute and Refund Evidence Vault',
    category: 'Risk',
    icon: ShieldAlert,
    summary: 'The evidence vault stores condition notes, testing proof, packing photos, tracking, buyer messages, and response templates.',
    why: 'Good evidence helps respond professionally to refunds, damage claims, missing item claims, and region compatibility issues.',
    steps: [
      'Open Planning, then Disputes.',
      'Link the dispute to an inventory item when possible.',
      'Add platform, order reference, buyer, tracking, reason, and claim amount.',
      'Review the generated response template.',
      'Record outcome and refund amount.',
    ],
  },
  {
    id: 'reports',
    title: 'Reports',
    category: 'Reporting',
    icon: Archive,
    summary: 'Reports and insights summarize sales, profit, source performance, aging inventory, and operational bottlenecks.',
    why: 'Reports help decide what to buy again, what to avoid, and where time or cash is getting stuck.',
    steps: [
      'Open Reports or Insights.',
      'Review best and worst categories, sources, platforms, and lots.',
      'Use the results to update buy guide rules.',
    ],
  },
  {
    id: 'settings',
    title: 'Settings',
    category: 'Admin',
    icon: Settings,
    summary: 'Settings control app preferences, aging alerts, integrations, and account behavior.',
    why: 'Central settings keep advanced controls out of daily work screens.',
    steps: [
      'Open Settings.',
      'Adjust aging alert thresholds or integration settings.',
      'Keep admin-only controls limited to trusted users.',
    ],
  },
  {
    id: 'troubleshooting',
    title: 'Troubleshooting',
    category: 'Support',
    icon: AlertTriangle,
    summary: 'Use troubleshooting when scans, pricing, imports, invites, or integrations do not behave as expected.',
    why: 'Most issues are caused by stale pricing, missing permissions, duplicate rows, or source data that needs review.',
    steps: [
      'Refresh the page and try the action once more.',
      'Check whether you are signed in as the right account.',
      'For pricing, open the item and refresh pricing directly.',
      'For imports, review duplicate prompts and required columns.',
      'For invites, confirm Supabase service role configuration is set in Netlify.',
    ],
  },
  {
    id: 'glossary',
    title: 'Glossary',
    category: 'Support',
    icon: HelpCircle,
    summary: 'Common terms used throughout RetroLootPro.',
    why: 'Shared language helps non-technical users understand the workflow.',
    steps: [
      'Cost basis: what the item effectively cost the business.',
      'Market value: current estimated resale value.',
      'Floor price: the lowest normal price before profit is too thin.',
      'Emergency floor: clearance price used only when cash recovery matters more than margin.',
      'Break-even: the point where sales have recovered the lot cost.',
      'Dead inventory: items sitting long enough to need price, photo, channel, or bundle action.',
    ],
  },
];

export const workflowGuides: ManualGuide[] = [
  {
    id: 'daily-workflow',
    title: 'Daily Workflow',
    summary: 'The daily routine for deciding what needs work first.',
    steps: [
      'Check the Dashboard.',
      'Review finance warnings and cash position.',
      'Review tasks due and aging inventory.',
      'Add, clean, test, photograph, price, or list priority items.',
      'Review sales and profit.',
      'Decide whether buying more inventory is safe today.',
    ],
  },
  {
    id: 'new-inventory-workflow',
    title: 'New Inventory Workflow',
    summary: 'Use this when new games, books, collectibles, or mixed lots arrive.',
    steps: [
      'Create the shipment or purchase record.',
      'Confirm receipt and create or attach the lot.',
      'Enter total paid, shipping, taxes, and fees.',
      'Scan UPCs or manually add titles.',
      'Add condition and testing notes.',
      'Refresh prices and allocate cost.',
      'Assign prep tasks and decide sales channel.',
    ],
  },
  {
    id: 'before-you-buy',
    title: 'Before You Buy Inventory',
    summary: 'Use this before spending money on a lot.',
    steps: [
      'Enter the potential lot in Lot Analyzer.',
      'Estimate resale value and worst-case value.',
      'Review max buy price and risk flags.',
      'Check safe buying budget and upcoming expenses.',
      'Make a buy, risky buy, or pass decision.',
    ],
  },
  {
    id: 'whatnot-workflow',
    title: 'Whatnot Show Workflow',
    summary: 'Prepare and review a live sale.',
    steps: [
      'Create the show.',
      'Add ready inventory.',
      'Set run order, starting bid, floor, BIN, and notes.',
      'Mark sold items and enter sale prices.',
      'Review post-show profit and update inventory status.',
    ],
  },
  {
    id: 'ebay-workflow',
    title: 'eBay Listing Workflow',
    summary: 'Prepare an item for eBay without losing the inventory connection.',
    steps: [
      'Select ready-to-list items.',
      'Generate title, description, and condition notes.',
      'Review pricing and floor warnings.',
      'Create a draft or mark listed.',
      'Store listing URL and update sold status when it sells.',
    ],
  },
  {
    id: 'finance-review',
    title: 'Finance Review Workflow',
    summary: 'Use this before buying more inventory or at the end of the week.',
    steps: [
      'Check cash available.',
      'Check upcoming expenses, debt, and tax reserve.',
      'Review lots not broken even.',
      'Review cash tied up in inventory.',
      'Set or adjust safe buying budget.',
      'Decide whether to buy, hold, discount, or liquidate.',
    ],
  },
  {
    id: 'dispute-workflow',
    title: 'Dispute Workflow',
    summary: 'Use this when a buyer opens a claim or requests a refund.',
    steps: [
      'Open the sold item or dispute case.',
      'Review photos, testing notes, packing proof, and tracking.',
      'Select the matching response template.',
      'Customize the response in a professional tone.',
      'Log the result, refund, or win/loss outcome.',
    ],
  },
];

export const manualFaq = [
  {
    question: 'What should I check first each day?',
    answer: 'Start with Dashboard, then Finance warnings, Tasks, and Aging Inventory. That shows whether you should list, prep, ship, discount, or hold cash.',
  },
  {
    question: 'When should I use Emergency Floor?',
    answer: 'Use Emergency Floor only when cash recovery matters more than normal margin, such as clearance, dead inventory, or a short-term cash need.',
  },
  {
    question: 'Why does cost basis change for lot items?',
    answer: 'Lot cost can be allocated by each item share of the total fair market value. Better items receive more of the cost than low-value filler items.',
  },
  {
    question: 'What makes an item dead inventory?',
    answer: 'An item becomes dead inventory when it sits beyond your aging threshold without selling. It may need a new price, photos, platform, bundle, or clearance action.',
  },
  {
    question: 'Can I add more than one copy of the same item?',
    answer: 'Yes. When a duplicate is detected, confirm whether it is a true second copy or an accidental repeat scan.',
  },
];
